---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(scales)
library(here)
library(knitr)
library(boot)
library("lubridate")
theme_set(theme_bw())
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
dataset1 = read_csv(here::here("/data/dataset01-yamada.csv"))
```


```{r}

dataset1 = dataset1 %>% 
    group_by(page) %>% 
    mutate(fp = wrong, 
           tp = extracted - wrong,
           fn = expected - tp,
           recall = tp/(tp + fn),
           precision = tp/(tp + fp),
           f_score = if (recall > 0 && precision > 0) { (2*recall*precision)/(recall+precision) }else { 0.0}) %>% ungroup()

dataset1$precision[is.na(dataset1$precision)] <- 0
dataset1$recall[is.na(dataset1$recall)] <- 0
recall = mean(dataset1$recall, na.rm=TRUE)
recall

precision = mean(dataset1$precision, na.rm=TRUE)
precision

f_score = (2*recall*precision)/(recall+precision)
f_score 

```
```{r}
set.seed(1234)

uma_amostra = sample_n(dataset1, 51)

uma_amostra
a <- dataset1 %>% select(precision, recall)
# a = sample_n(a, 100, replace = TRUE )
funcao_bootstrap <- function(dado, indices){
    print(dado)
    a <- mean(dado$precision[indices])
    b <- mean(dado$recall[indices])
    c(a,b)
}

# funcao_bootstrap <- function(x, i){
#     print(x)
#     mean(x[i])
# }

bootstraps <- boot(data = dataset1, 
                   statistic = funcao_bootstrap, # <- referência para a função 
                   R = 2000) # número de bootstraps
glimpse(bootstraps$t)

boot.ci(bootstraps, conf = 0.95, type = "basic")

```


