---
title: "lab05_CP 2:_Beleza_e_avaliação"
output: html_document
---

```{r warning=FALSE, echo=FALSE}
library(tidyverse)
library(broom)
library(modelr)
```

```{r read}
avaliacao_professores = read_csv(here::here("data/evals.csv"))

avaliacao_professores
```
```{r}
avaliacao_professores %>% 
  ggplot(aes(x = age)) + 
  geom_histogram(bins = 20) +
  facet_grid(gender ~ .)

avaliacao_professores %>% 
  ggplot(aes(x = age)) + 
  geom_histogram(bins = 20) +
  facet_grid(ethnicity ~ .)

avaliacao_professores %>% 
  ggplot(aes(x = bty_avg)) + 
  geom_histogram(bins = 20) +
  facet_grid(gender ~ .)

avaliacao_professores %>% 
  ggplot(aes(x = bty_avg)) + 
  geom_histogram(bins = 20) +
  facet_grid(cls_level ~ .)

avaliacao_professores %>% 
  ggplot(aes(x = bty_avg)) + 
  geom_histogram(bins = 20) +
  facet_grid(rank ~ .)

avaliacao_professores %>% 
  ggplot(aes(x = score)) + 
  geom_histogram(bins = 20) +
  facet_grid(rank ~ .)

avaliacao_professores %>% 
  ggplot(aes(x = score)) + 
  geom_histogram(bins = 20) +
  facet_grid(gender ~ .)

avaliacao_professores %>% 
  ggplot(aes(x = score, y = bty_avg)) + 
  geom_point() +
  facet_grid(gender ~ .)

avaliacao_professores %>% 
  ggplot(aes(x = score, y = bty_avg)) + 
  geom_point()

```


##Média beleza e score professores

```{r}
modelo1 <- lm(score ~ bty_avg, data = avaliacao_professores)

tidy(modelo1, conf.int = TRUE, conf.level = 0.95)
glance(modelo1)

```

##idade e score professores

```{r}
modelo2 <- lm(score ~ rank, data = avaliacao_professores)

tidy(modelo2, conf.int = TRUE, conf.level = 0.95)
glance(modelo2)

```

